### ISSUE TITLE
How to interactive with the Contract

### ISSUE THREAD

**Issue by liusanchuan** [SeanJCasey/truffle-compound-sandbox#2]
Hi, thanks very much for your work, which makes me easier to learn compound.
But as a new hand, I don't know how to interact with the smart contract. 
Can you give me some advice or example, such as how to send ether to mint?

**Comment by SeanJCasey** [comment]
Glad you found this helpful!

Compound has extensive docs on interacting with their protocol: https://compound.finance/docs#guides

Check out guide #2 for how to "supply" (i.e., mint). Just search that page for "mint" and you'll find code snippets that will hopefully help.
